# Generated by Django 4.1.3 on 2022-11-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combinacionSecreta', models.TextField(verbose_name='[]')),
            ],
        ),
    ]
